# Generated by Django 3.2.4 on 2021-06-08 15:08

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=120)),
                ('place_photo', models.URLField(max_length=300)),
                ('place_address', models.CharField(blank=True, max_length=300)),
                ('place_station', models.CharField(blank=True, max_length=120)),
                ('place_description', models.TextField()),
                ('place_rating', models.FloatField()),
                ('place_tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
