# Generated by Django 3.2.4 on 2021-06-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
