# Generated by Django 3.2.4 on 2021-06-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_photo',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_station',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
