# Generated by Django 3.2.4 on 2021-06-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0002_auto_20210607_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='place_url',
        ),
        migrations.AlterField(
            model_name='place',
            name='place_description',
            field=models.TextField(),
        ),
    ]
