# Generated by Django 3.2.4 on 2021-06-10 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0003_auto_20210610_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='place_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='place_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='place_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='place_photo',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='place_rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='place_station',
            new_name='station',
        ),
    ]
