# Generated by Django 3.2.4 on 2021-06-11 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0008_alter_tag_value'),
        ('account', '0004_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomizer.place', verbose_name='Место')),
            ],
            options={
                'db_table': 'user_favorites',
            },
        ),
    ]
