# Generated by Django 3.2.4 on 2021-06-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0004_auto_20210610_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='cards',
            field=models.ManyToManyField(to='randomizer.Place'),
        ),
    ]
