# Generated by Django 3.2.4 on 2021-06-07 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0004_place_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='users',
        ),
    ]
