# Generated by Django 3.2.4 on 2021-06-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0005_tag_cards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='cards',
        ),
        migrations.AddField(
            model_name='place',
            name='tags',
            field=models.ManyToManyField(to='randomizer.Tag'),
        ),
    ]
