# Generated by Django 3.2.4 on 2021-06-08 03:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('randomizer', '0005_remove_place_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='favourite',
            field=models.ManyToManyField(related_name='user_favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
