# Generated by Django 3.2.4 on 2021-06-08 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0006_place_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='favourite',
        ),
    ]
