# Generated by Django 3.2.4 on 2021-06-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0006_auto_20210610_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag_name',
            new_name='text',
        ),
        migrations.AddField(
            model_name='tag',
            name='value',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
