# Generated by Django 3.2.4 on 2021-06-11 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0008_auto_20210611_0631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag_value',
            new_name='value',
        ),
    ]
