# Generated by Django 3.2.4 on 2021-06-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0008_alter_tag_value'),
        ('account', '0005_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(to='randomizer.Place'),
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
